name: cube_alg_analyser
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

flutter:
  uses-material-design: true
  assets:
    - assets/cubing/
    - assets/

# Scripts to be run with rps
scripts:
  init: flutter pub get
  clean: flutter clean
  refresh: flutter clean; flutter pub get
  test: flutter test
  analise: dart analyze
  fix: dart fix --dry-run
  freezed:
    build: flutter pub run build_runner build --delete-conflicting-outputs
  web:
    build:  flutter build web --release --source-maps --no-tree-shake-icons --output docs --base-href /cube_alg_analyser/

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod:
  font_awesome_flutter: ^10.5.0
  freezed:
  freezed_annotation:
  go_router:
  json_annotation: ^4.8.1
  webview_flutter: ^4.4.2
#  webview_flutter_android: ^3.12.1
  webview_flutter_web: ^0.2.2+3
  webview_flutter_wkwebview: ^3.9.4
  webview_universal: ^0.0.5
  wt_app_scaffold:
    git: https://github.com/tmcmaster/wt_app_scaffold.git
  wt_logging:
    git: https://github.com/tmcmaster/wt_logging.git
  wt_models:
    git: https://github.com/tmcmaster/wt_models.git
  wt_settings:
    git: https://github.com/tmcmaster/wt_settings.git


dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable:

#dependency_overrides:
#  wt_app_scaffold:
#    path: ../../libraries/wt_app_scaffold
#  wt_settings:
#    path: ../../libraries/wt_settings
