name: cube_alg_analyser
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

flutter:
  uses-material-design: true
  assets:
    - assets/cubing/

# Scripts to be run with rps
scripts:
  init: flutter pub get
  clean: flutter clean
  refresh: flutter clean; flutter pub get
  test: flutter test
  analise: dart analyze
  fix: dart fix --dry-run
  freezed:
    build: flutter pub run build_runner build --delete-conflicting-outputs

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod:
  freezed:
  freezed_annotation:
  json_annotation: ^4.8.1
  wt_logging:
    git: https://github.com/tmcmaster/wt_logging.git
  wt_models:
    git: https://github.com/tmcmaster/wt_models.git

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: